import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { Suspense } from "react";

const inter = Red_Hat_Display({ subsets: ["latin"] });

export const metadata = {
  title: "InstaStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Header />
          <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
        </main>
      </body>
    </html>
  );
}
